### ISSUE TITLE
Vivo Fibra no UDM

### ISSUE THREAD

**Issue by galvesribeiro** [offspringer/unifi-usg-vivo-fibra#1]
Olá!

Estou tentando adaptar o que você fez pro USG em um UDM ou seja, ter o Vivo Fibra Internet e IPTV funcionando.

Como não existe mais o config.gateway.json no UDM, você tem ideia do que fazer para que isso funcione? 

O meu caso eu comprei um ONT TP-Link para conectar a fibra. Para efeito de testes, fiz ele marcar a VLAN 10 e configurei o GPON PW/SN e conectei via PC. Conectou normalmente. 

Na sequência, fiz o ONT rodar com as VLANs em "Transparent Mode" e pluguei ele na WAN do UDM. Assim como no USG, a porta WAN pela UI Web apenas permite estar a VLAN da internet, no caso a 10. Feito isso a configuração PPPoE feita no USG e a internet também funciona. 

O problema começa com o IPTV... Tentei fazer essa gambiarra aqui:

<img width="1499" alt="image" src="https://user-images.githubusercontent.com/4714040/111344476-27a1e780-865b-11eb-8171-b39948e4cef0.png">

Criei 2 Networks "VLAN-only" para a 10 e a 20. Dai setei o Port Profile como mostra na imagem só que ao invés de ligar o ONT na porta WAN direto, eu liguei ele em uma das portas do UDM, e liguei outra porta d UDM na WAN e coloquei ambas portas na VLAN 10. Internet funcionou também.

O problema são os decoders/STB da Vivo. Quando eu plugo eles em outra porta e set o Port Profile pra VLAN20, eles até pegam IP, mas não seguem o fluxo de boot e ficam parados no logo VIVO.

Você teria alguma idéia do que fazer???

Estou na Vivo São Paulo, se você quiser falar offline via Skype ou outra coisa só me falar.

Obrigado!

[]s
Gutemberg

**Comment by offspringer** [comment]
Opa, tudo bem?

Também consegui montar este setup em um EdgeRouter-X e percebi algumas
coisas que foram cruciais para funcionar no USG, e que foram diferentes do
ER-X.
Por exemplo, desabilitar o IP Source Validation na VLAN 20 foi essencial.
No ER-X você faz isso direto no firewall.
Tem também a questão da rota estática 0.0.0.0/0 para pppoe0, que o ER-X
deixa fazer até pela interface web, enquanto o USG não permite.

Eu já vi bastante gente fazendo essa gambiarra que você mencionou, mas não
cheguei a explorar muito.
Pelo erro que você está tendo, eu acho dá pra eliminar problemas com proxy
IGMP.
Você já configurou todas as rotas estáticas e as regras de firewall?




Em ter., 16 de mar. de 2021 às 13:29, Gutemberg Ribeiro <
***@***.***> escreveu:

**Comment by galvesribeiro** [comment]
Então, onde que tem essas regras de firewall e rotas?

Acabei comprando um USG e instalei o controller numa Raspberry pra ter o setup exatamente igual o do seu exemplo mas acabou que não funcionou também... 

Na hora de forçar o provisioning, ele ficou em loop:

<img width="743" alt="image" src="https://user-images.githubusercontent.com/4714040/111429341-a63c6a80-86d7-11eb-8d2c-ea7cc8abc52d.png">

**Comment by galvesribeiro** [comment]
O grande lance é que tanto o ER(-X) quanto o USG usam o mesmo OS, o EdgeOS, então as configs devem ser bem semelhantes.

O ideal pra mim seria poder replicar a mesma coisa no UDM, que usa o novo UnifiOS mas se não for possível, ap menos queria conseguir usar os seus configs/scripts no USG.

**Comment by galvesribeiro** [comment]
Só pra te dar um retorno. Eu desisti...

Aproveitei o embalo e cancelei o IPTV da Vivo. Assinei os canais que eu assistia via Streaming, e to usando meu UDM agora. Agora só tenho link de fibra e nada mais.

Mesmo assim valeu pela ajuda!

[]s

**Comment by haroldofurtado** [comment]
> O grande lance é que tanto o ER(-X) quanto o USG usam o mesmo OS, o EdgeOS, então as configs devem ser bem semelhantes.
> 
> O ideal pra mim seria poder replicar a mesma coisa no UDM, que usa o novo UnifiOS mas se não for possível, ap menos queria conseguir usar os seus configs/scripts no USG.

O que acontece é que a depender da região a coisa muda um pouco de cenário. O que daria pra fazer (se é que você ainda tem o equipamento seria alterar as configurações padrões.

**Comment by apedroheringer** [comment]
Eu consegui fazer funcionar no meu udm pro com esse repo, so não to conseguindo usar o on demand
https://github.com/fabianishere/udm-iptv
Os ranges de ips para configuracao peguei daqui!

**Comment by cawv** [comment]
Oi pessoal, vi que o problema real é a falta da implementação nativa do IGMP proxy na UDM, coisa nativa no edge e USG e não entregue pela Ubiquiti.
Quem tentou pela solução complexa do Fabiani travou na parte da interação, mas li algo sobre um caso na Espanha (telefônica) que usa o mesmo modem Askey e com uso da USG switches para untag a Vlan na ponta a coisa funciona perfeito.
